ref: "reference_sets/USA"

min_ab: 1
tot_cov: 10
spike_only: true

bootstraps: 10

vocs: ["B.1.1.7", "B.1.351", "B.1.617.2", "P.1"]
lineages: ["1008906", "1001460", "1924762", "1194849"]

abundances:
  [
    0.05,
    0.06,
    0.07,
    0.08,
    0.09,
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    20,
    30,
    40,
    50,
    60,
    70,
    80,
    90,
    100,
  ]
