ref: "reference_sets/USA"

min_ab: 0.1
tot_cov: 100
spike_only: True

bootstraps: 0

vocs: ["B.1.1.7"]
lineages: ["1008906"]
# vocs: ["B.1.1.7", "B.1.351", "B.1.617.2", "P.1"]
# lineages: ["1008906", "1001460", "1924762", "1194849"]

plot_exts: ["png"]
plot_error_value: 0
plot_abundance_value: 10

errors_scale_log: False
errors_log: [0.001, 10, 32]

errors: # %
  [0, 0.01, 0.1, 1, 10]

abundances_scale_log: False
abundances_log: [0.1, 100, 32]

abundances: [10.0]
# abundances:
#   [
#     0.05,
#     0.06,
#     0.07,
#     0.08,
#     0.09,
#     0.1,
#     0.2,
#     0.3,
#     0.4,
#     0.5,
#     0.6,
#     0.7,
#     0.8,
#     0.9,
#     1,
#     2,
#     3,
#     4,
#     5,
#     6,
#     7,
#     8,
#     9,
#     10,
#     20,
#     30,
#     40,
#     50,
#     60,
#     70,
#     80,
#     90,
#     100,
#   ]
